# binance API
binance_apikey = "api"
binance_apisecret = "api_secret"
# okx API
okx_apikey = "api"
okx_apisecret = "api_secret"
okx_passphrase = "pass"
# bybit API
bybit_apikey = "api"
bybit_apisecret = "api_secret"
# gate API
gate_apikey = "api"
gate_apisecret = "api_secret"
# kucoin API
kucoin_apikey = "api"
kucoin_apisecret = "api_secret"
kucoin_passphrase = "api_password"
# mexc API
mexc_apikey = "api"
mexc_apisecret = "api_secret"
# huobi API
huobi_apikey = "api"
huobi_apisecret = "api_secret"
